### PR TITLE
ziggurat: execute hoon on %pyro-agent-state scry

### PR DESCRIPTION
**Pull request by hosted-fornet**
**Problem**:

Want to have more `:my-app +dbug [%state (~(get by my-map) 0xdead.beef)]` type flexibility for querying agent state.

**Solution**:

Copy-paste from [lib/dbug.hoon](https://github.com/urbit/urbit/blob/develop/pkg/base-dev/lib/dbug.hoon#L53-L55).

**Notes**:

Not quite working for FE yet. E.g., from Urbit:
```hoon
> =zig -build-file /=zig=/sur/zig/ziggurat/hoon
> .^(update:zig %gx /=ziggurat=/pyro-agent-state/~nec/uqbar/''/noun)
[ %pyro-agent-state
  [project-name='' source=%pyro-agent-state request-id=~]
    payload
  [ %.y
      p
    [ agent-state='[ %0\0a  indexers={[p=0x0 q=[p=~nec q=%indexer]]}\0a    sequencers\0a  {[p=0x0 q=[p=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 q=~nec]]}\0a  wallet-source=%wallet\0a]\0a'
      wex={[p=[wire=/capitol-updates ship=~nec term=%indexer] q=[acked=%.y path=/capitol-updates]] [p=[wire=/indexer/wallet/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]]}
      sup={[p=~[/gall/use/subscriber/0wNZlXL/out/~nec/uqbar/1/~nec/uqbar/track /dill //term/1] q=[p=~nec q=/track]] [p=~[/gall/use/wallet/0wHIhBI/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/wallet/batch-order/0x0]]}
    ]
  ]
  ~
]


> .^(update:zig %gx /=ziggurat=/pyro-agent-state/~nec/uqbar/'indexers'/noun)
[ %pyro-agent-state
  [project-name='' source=%pyro-agent-state request-id=~]
    payload
  [ %.y
      p
    [ agent-state='{[p=0x0 q=[p=~nec q=%indexer]]}\0a'
      wex={[p=[wire=/capitol-updates ship=~nec term=%indexer] q=[acked=%.y path=/capitol-updates]] [p=[wire=/indexer/wallet/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]]}
      sup={[p=~[/gall/use/subscriber/0wNZlXL/out/~nec/uqbar/1/~nec/uqbar/track /dill //term/1] q=[p=~nec q=/track]] [p=~[/gall/use/wallet/0wHIhBI/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/wallet/batch-order/0x0]]}
    ]
  ]
  ~
]


> .^(update:zig %gx /=ziggurat=/pyro-agent-state/~nec/uqbar/'(~(get by indexers) 0x0)'/noun)
[ %pyro-agent-state
  [project-name='' source=%pyro-agent-state request-id=~]
    payload
  [ %.y
      p
    [ agent-state='[~ [p=~nec q=%indexer]]\0a'
      wex={[p=[wire=/capitol-updates ship=~nec term=%indexer] q=[acked=%.y path=/capitol-updates]] [p=[wire=/indexer/wallet/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]]}
      sup={[p=~[/gall/use/subscriber/0wNZlXL/out/~nec/uqbar/1/~nec/uqbar/track /dill //term/1] q=[p=~nec q=/track]] [p=~[/gall/use/wallet/0wHIhBI/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/wallet/batch-order/0x0]]}
    ]
  ]
  ~
]
```
whereas from the frontend, the first two work, but the third does not:
```bash
$ export NEC_COOKIE=$(curl -i -X POST localhost:8080/~/login -d 'password=ropnys-batwyd-nossyt-mapwet' | grep set-cookie | awk '{print $2}' | awk -F ';' '{print $1}')
$ curl --cookie "$NEC_COOKIE" localhost:8080/~/scry/ziggurat/pyro-agent-state/~nec/uqbar/-.json | jq
{
  "source": "pyro-agent-state",
  "request_id": null,
  "data": {
    "incoming": [
      {
        "duct": [
          "/gall/use/wallet/0wHIhBI/out/~nec/uqbar/1/new-batch",
          "/dill",
          "//term/1"
        ],
        "ship": "~nec",
        "path": "/indexer/wallet/batch-order/0x0"
      },
      {
        "duct": [
          "/gall/use/subscriber/0wNZlXL/out/~nec/uqbar/1/~nec/uqbar/track",
          "/dill",
          "//term/1"
        ],
        "ship": "~nec",
        "path": "/track"
      }
    ],
    "outgoing": [
      {
        "term": "indexer",
        "ship": "~nec",
        "wire": "/indexer/wallet/batch-order/0x0",
        "path": "/batch-order/0x0",
        "acked": true
      },
      {
        "term": "indexer",
        "ship": "~nec",
        "wire": "/capitol-updates",
        "path": "/capitol-updates",
        "acked": true
      }
    ],
    "pyro-agent-state": "[ %0\n  indexers={[p=0x0 q=[p=~nec q=%indexer]]}\n    sequencers\n  {[p=0x0 q=[p=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 q=~nec]]}\n  wallet-source=%wallet\n]\n"
  },
  "project_name": "",
  "type": "pyro-agent-state"
}


$ curl --cookie "$NEC_COOKIE" localhost:8080/~/scry/ziggurat/pyro-agent-state/~nec/uqbar/indexers.json | jq
{
  "source": "pyro-agent-state",
  "request_id": null,
  "data": {
    "incoming": [
      {
        "duct": [
          "/gall/use/wallet/0wHIhBI/out/~nec/uqbar/1/new-batch",
          "/dill",
          "//term/1"
        ],
        "ship": "~nec",
        "path": "/indexer/wallet/batch-order/0x0"
      },
      {
        "duct": [
          "/gall/use/subscriber/0wNZlXL/out/~nec/uqbar/1/~nec/uqbar/track",
          "/dill",
          "//term/1"
        ],
        "ship": "~nec",
        "path": "/track"
      }
    ],
    "outgoing": [
      {
        "term": "indexer",
        "ship": "~nec",
        "wire": "/indexer/wallet/batch-order/0x0",
        "path": "/batch-order/0x0",
        "acked": true
      },
      {
        "term": "indexer",
        "ship": "~nec",
        "wire": "/capitol-updates",
        "path": "/capitol-updates",
        "acked": true
      }
    ],
    "pyro-agent-state": "{[p=0x0 q=[p=~nec q=%indexer]]}\n"
  },
  "project_name": "",
  "type": "pyro-agent-state"
}


$ curl --cookie "$NEC_COOKIE" localhost:8080/~/scry/ziggurat/pyro-agent-state/~nec/uqbar/(~(get by indexers) 0x0).json | jq
bash: syntax error near unexpected token `('
```

### CODE REVIEW

**Comment by hosted-fornet** [comment]
Any ideas how to get an arbitrary string to be acceptable in a URL-encoded endpoint @0x70b1a5 ?

If this doesn't work, we can potentially do something like `+jam` the hoon and then `+cue` it urbit-side, but unless there is a JS `+jam` implementation floating around that could be annoying to do.

**Comment by 0x70b1a5** [comment]
Endpoints are not the ideal place to pass arbitrary strings to the BE.
I have two questions:

1. Does #3 work if you hit F12 on the Ziggurat app and type `await
api.scry({ app: 'ziggurat', path: '/pyro-agent-state/~nec/uqbar/(~(get
by indexers) 0x0)' })` ?
2. If 1 does not succeed, are you morally opposed to implementing this
as a poke?

**Comment by hosted-fornet** [comment]
Just confirmed the API in 1 does not work: I think this just converts to a `/~/scry/...` under the hood, so it makes sense it would not work.

How does the information propagate back to the FE? Through a subscription update? That could work.

**Comment by 0x70b1a5** [comment]
Would it make sense as another project-update? Or should it be a different subscription?

**Comment by hosted-fornet** [comment]
Yeah, I'll add it as a subscription update on the same path you already subscribe to (unless you want it on a different path).

**Comment by 0x70b1a5** [comment]
Same path works great.

**Comment by hosted-fornet** [comment]
Done in b92cd47. Keeping the scry endpoint around for now. I tested that it works in-urbit, but its harder for me to test pokes from the outside.

**Comment by hosted-fornet** [comment]
https://github.com/uqbar-dao/uqbar-core/blob/b92cd47cfb30f9cbb3cab6659ea139071cdb0d2d/sur/zig/ziggurat.hoon#L164

**Comment by hosted-fornet** [comment]
```hoon
> -zig!ziggurat-test-subscribe %zig 1.000


[ %zts
  %ziggurat-update
  "update=[%pyro-agent-state [project-name='' source=%pyro-agent-state request-id=~] payload=[%.y p=[agent-state='[ %0\\0a  indexers=\{[p=0x0 q=[p=~nec q=%indexer]]}\\0a    sequencers\\0a  \{[p=0x0 q=[p=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 q=~nec]]}\\0a  wallet-source=%wallet\\0a]\\0a' wex=\{[p=[wire=/indexer/pokur-host/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]] [p=[wire=/capitol-updates ship=~nec term=%indexer] q=[acked=%.y path=/capitol-updates]] [p=[wire=/indexer/wallet/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]]} sup=\{[p=~[/gall/use/wallet/0w1.cJxLu/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/wallet/batch-order/0x0]] [p=~[/gall/use/subscriber/0w3.uaSAW/out/~nec/uqbar/1/~nec/uqbar/track /dill //term/1] q=[p=~nec q=/track]] [p=~[/gall/use/pokur-host/0w-ab3G/out/~nec/uqbar/1/new
-batch /dill //term/1] q=[p=~nec q=/indexer/pokur-host/batch-order/0x0]]}]] ~]"
]
> :ziggurat &ziggurat-action [%zig `%get-state %pyro-agent-state ~nec %uqbar '']
>=


[ %zts
  %ziggurat-update
  "update=[%pyro-agent-state [project-name='' source=%pyro-agent-state request-id=~] payload=[%.y p=[agent-state='[~ [p=~nec q=%indexer]]\\0a' wex=\{[p=[wire=/indexer/pokur-host/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]] [p=[wire=/capitol-updates ship=~nec term=%indexer] q=[acked=%.y path=/capitol-updates]] [p=[wire=/indexer/wallet/batch-order/0x0 ship=~nec term=%indexer] q=[acked=%.y path=/batch-order/0x0]]} sup=\{[p=~[/gall/use/wallet/0w1.cJxLu/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/wallet/batch-order/0x0]] [p=~[/gall/use/subscriber/0w3.uaSAW/out/~nec/uqbar/1/~nec/uqbar/track /dill //term/1] q=[p=~nec q=/track]] [p=~[/gall/use/pokur-host/0w-ab3G/out/~nec/uqbar/1/new-batch /dill //term/1] q=[p=~nec q=/indexer/pokur-host/batch-order/0x0]]}]] ~]"
]
> :ziggurat &ziggurat-action [%zig `%get-state-get-by-indexers %pyro-agent-state ~nec %uqbar '(~(get by indexers) 0x0)']
```

**Pull request merged**
