### PR TITLE
ziggurat: tests

### PR DESCRIPTION
**Pull request by hosted-fornet**
WIP

### CODE REVIEW

**Comment by dr-frmr** [comment]
looks fire

**Comment by hosted-fornet** [comment]
Oof. Diff got rekt cuz I merged in `da/pyro`. Will have to figure out how to un-rekt diff before review. Fortunately that won't be for a little while.

**Comment by hosted-fornet** [comment]
```
:pyro &pill +solid %base %zig
:pyro &aqua-events ~[[%init-ship ~nec] [%init-ship ~bud] [%init-ship ~wes]]

=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]

=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-seqeuncer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup-wes `test-steps:zig`~[[%poke [~wes %indexer %set-seqeuncer '[~nec %sequencer]'] ~] [%poke [~wes %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~wes %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~wes %uqbar %wallet-poke '[%import-seed \'flee alter erode parrot turkey harvest pass combine casual interest receive album coyote shrug envelope turtle broken purity wear else fluid transaction theme buyer\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`;:(weld setup-nec setup-bud setup-wes)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]

=test-id 0x5c1b.ca05
:ziggurat &ziggurat-action [%foo %run-test test-id 1 1.000.000]
```

**Comment by dr-frmr** [comment]
If you target the pyro branch does that fix the diff issue?

**Comment by hosted-fornet** [comment]
> If you target the pyro branch does that fix the diff issue?

If we brought next/smart into that branch, yeah, it should.

**Comment by dr-frmr** [comment]
Let's merge the `dr/pyro-aqua-fork` branch into `next/smart`, then

**Comment by hosted-fornet** [comment]
How I am currently testing:

```
:pyro &pill +zig!solid %base %zig
:pyro &aqua-events ~[[%init-ship ~nec] [%init-ship ~bud]]
=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]
|start %zig %pyro-sub
:pyro-sub [%sub ~]
=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-sequencer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`(weld setup-nec setup-bud)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]
=scry-nec `test-steps:zig`~[[%dojo [rollup-host '=ui -build-file /=zig=/sur/zig/indexer/hoon'] ~] [%dojo [rollup-host '.^(update:ui %gx /=indexer=/batch-order/0x0/noun)'] ~]]
:ziggurat &ziggurat-action [%foo %add-test `%scry-nec scry-nec]
=scry-bud `test-steps:zig`~[[%dojo [~bud '=ui -build-file /=zig=/sur/zig/indexer/hoon'] ~] [%dojo [~bud '.^(update:ui %gx /=indexer=/batch-order/0x0/noun)'] ~]]
:ziggurat &ziggurat-action [%foo %add-test `%scry-bud scry-bud]
=scry-bud-id 0xa1d4.5837.9dcc.7911.71cf.fdd0.c048.e790
=scry-nec-id 0xfe66.017b.f86f.de50.1ce9.d366.e836.bbaa
=setup-id 0xa253.baf1.f666.df41.ab31.fe25.2de6.5d20


:ziggurat &ziggurat-action [%foo %run-test setup-id 1 1.000.000]
```

**Comment by hosted-fornet** [comment]
Merged PR #213 into `next/smart` and rebased this PR. This PR contains commits by dachus from PR #242: they got rewritten in the rebase to look like they are from me.

**Comment by hosted-fornet** [comment]
Current testing:

```
:pyro &pill +zig!solid %base %zig
:pyro &aqua-events ~[[%init-ship ~nec] [%init-ship ~bud]]
=zig -build-file /=zig=/sur/zig/ziggurat/hoon
=rollup-host ~nec
:ziggurat &ziggurat-action [%foo %new-project 0x1234.5678]
|start %zig %pyro-sub
:pyro-sub [%sub ~]
=setup-nec `test-steps:zig`~[[%dojo [rollup-host ':rollup|activate'] ~] [%dojo [rollup-host ':sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608'] ~] [%poke [rollup-host %indexer %set-sequencer '[our %sequencer]'] ~] [%poke [rollup-host %indexer %set-rollup '[our %rollup]'] ~] [%poke [rollup-host %uqbar %wallet-poke '[%import-seed \'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove\' \'squid\' \'nickname\']'] ~]]
=setup-bud `test-steps:zig`~[[%poke [~bud %indexer %set-sequencer '[~nec %sequencer]'] ~] [%poke [~bud %indexer %set-rollup '[~nec %rollup]'] ~] [%poke [~bud %indexer %indexer-bootstrap '[~nec %indexer]'] ~] [%poke [~bud %uqbar %wallet-poke '[%import-seed \'post fitness extend exit crack question answer fruit donkey quality emotion draw section width emotion leg settle bulb zero learn solution dutch target kidney\' \'squid\' \'nickname\']'] ~]]
=setup `test-steps:zig`(weld setup-nec setup-bud)
:ziggurat &ziggurat-action [%foo %add-test `%setup setup]
=scry-nec `test-steps:zig`~[[%dojo [rollup-host '=ui -build-file /=zig=/sur/zig/indexer/hoon'] ~] [%dojo [rollup-host '.^(update:ui %gx /=indexer=/batch-order/0x0/noun)'] ~]]
:ziggurat &ziggurat-action [%foo %add-test `%scry-nec scry-nec]
=scry-bud `test-steps:zig`~[[%dojo [~bud '=ui -build-file /=zig=/sur/zig/indexer/hoon'] ~] [%dojo [~bud '.^(update:ui %gx /=indexer=/batch-order/0x0/noun)'] ~]]
:ziggurat &ziggurat-action [%foo %add-test `%scry-bud scry-bud]
=scry-bud-id 0xa1d4.5837.9dcc.7911.71cf.fdd0.c048.e790
=scry-nec-id 0xfe66.017b.f86f.de50.1ce9.d366.e836.bbaa
=setup-id 0xa253.baf1.f666.df41.ab31.fe25.2de6.5d20

::  must wait until see 
::  [who=~nec %unknown-effect wire=/newt/0v1n.2m9vh card=[p=%turf q=0]]
::  [who=~bud %unknown-effect wire=/newt/0v1n.2m9vh card=[p=%turf q=0]]                      
::  in terminal before running anything after %start-test-master
::  TODO: make this robust
:ziggurat &ziggurat-action [%foo %start-test-master ~]

:ziggurat &ziggurat-action [%foo %run-test setup-id 1 1.000.000]

:ziggurat &ziggurat-action [%foo %run-test scry-bud-id 1 1.000.000]

:ziggurat &ziggurat-action [%foo %run-test scry-nec-id 1 1.000.000]

::  running will reset virtual ships; %stop then %start to refresh ship state
:ziggurat &ziggurat-action [%foo %stop-test-master ~]

:pyro|dojo ~nec ":indexer +dbug %bowl"
:pyro|dojo ~bud ":indexer +dbug %bowl"

::  can submit txs!
::  there is something weird going on with errorcode: TODO figure it out
:pyro|dojo ~nec ":uqbar &wallet-poke [%transaction from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 contract=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 action=[%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 item=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6]]"
:pyro|dojo ~nec ":uqbar &wallet-poke [%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 hash=0xa99c.4c8e.1c8d.abb8.e870.81e8.8c96.2cf5 gas=[rate=1 bud=1.000.000]]"
:pyro|dojo ~nec ":sequencer|batch"
```

**Pull request merged**
